Repository Optum/barista, pull requests merged in 2020-08, with the labels that each got.

#205 Update project stats display
  barista-web/src/app/features/projects/project-details/project-details.component.scss
  barista-web/src/app/features/projects/project-details/project-stats/project-stats.component.html
  barista-web/src/app/features/projects/project-details/project-stats/project-stats.component.scss
Labels: enhancement

#207 Feature/dash documentation
  barista-web/docs/charts.md
  doc/images/barista-dashboard.png
  doc/images/barista-login.png
  doc/images/barista-organization-projects.png
  doc/images/barista-project-obligations.png
  doc/images/barista-project-summary-license.png
  doc/images/barista-project-summary-vulnerability.png
Labels: documentation

#208 Dashboard bugfixes and improvements
  barista-web/docs/charts.md
  barista-web/src/app/features/auth/auth.service.ts
  barista-web/src/app/features/dashboard/dashboard.component.ts
  barista-web/src/app/features/home/banner/banner.component.ts
  barista-web/src/app/features/home/chart-bar-horizontal/chart-bar-horizontal.component.ts
  barista-web/src/app/features/home/chart-bar-vertical/chart-bar-vertical.component.ts
  barista-web/src/app/features/home/chart-gauge/chart-gauge.component.ts
  barista-web/src/app/features/home/home.component.scss
  barista-web/src/app/features/home/home.component.ts
  barista-web/src/app/features/projects/project-details/project-details.component.scss
  barista-web/src/app/features/projects/project-details/project-details.component.ts
  barista-web/src/app/features/projects/project-details/project-stats/project-stats.component.html
  barista-web/src/app/features/projects/project-details/project-stats/project-stats.component.scss
  barista-web/src/app/features/projects/project-details/project-stats/project-stats.component.ts
  barista-web/src/app/features/projects/project-scans/project-scan-details/project-scan-details.component.ts
  barista-web/src/app/shared/+state/project/project.service.ts
  barista-web/src/app/shared/app-components/help-menu/help-menu.component.html
  barista-web/src/app/shared/app-components/help-menu/help-menu.component.ts
  barista-web/src/app/shared/layout/header/header.component.html
  barista-web/src/app/shared/layout/header/header.component.ts
  doc/images/barista-dashboard.png
  doc/images/barista-login.png
  doc/images/barista-organization-projects.png
  doc/images/barista-project-obligations.png
  doc/images/barista-project-summary-license.png
  doc/images/barista-project-summary-vulnerability.png
Labels: documentation, enhancement

#210 Update to Deep Link navigation
  barista-web/src/app/features/auth/auth.service.ts
  barista-web/src/app/shared/helpers/AuthInterceptor.ts
Labels: enhancement

#211 Feature/projectlist
  barista-api/src/controllers/stats/stats.controller.ts
  barista-scan/Dockerfile
  barista-web/src/app/app.module.ts
  barista-web/src/app/features/home/banner/banner.component.ts
  barista-web/src/app/features/home/home.component.ts
  barista-web/src/app/features/projects/project-details/project-details.component.html
  barista-web/src/app/shared/api/api/stats-api.service.ts
  barista-web/src/app/shared/helpers/managehttp.interceptor.ts
  barista-web/src/app/shared/services/httpcancel.service.ts
Labels: enhancement

#216 Update home.component.html
  barista-web/src/app/features/home/home.component.html
Labels: documentation

#220 update readme
  README.md
Labels: documentation
