Repository Optum/barista, pull requests merged in 2020-11, with the labels that each got.

#231 add wildcard route to catch bad routes
  barista-web/src/app/app-routing.module.ts
Labels: bug

#273 Update docusaurus.config.js
  doc/barista-docs/docusaurus.config.js
Labels: dependencies, documentation

#274 Update docusaurus.config.js
  doc/barista-docs/docusaurus.config.js
Labels: bug, documentation
