Repository Optum/barista, pull requests merged in 2020-07, with the labels that each got.

#138 adds bar chart functionality and sorting
  barista-web/src/app/features/projects/project-details/project-stats/project-stats.component.spec.ts
  barista-web/src/app/features/projects/project-details/project-stats/project-stats.component.ts
  barista-web/src/app/shared/app-components/app-components.module.ts
  barista-web/src/app/shared/app-components/charts/bar-chart/bar-chart.component.html
  barista-web/src/app/shared/app-components/charts/bar-chart/bar-chart.component.scss
  barista-web/src/app/shared/app-components/charts/bar-chart/bar-chart.component.spec.ts
  barista-web/src/app/shared/app-components/charts/bar-chart/bar-chart.component.ts
  barista-web/src/app/shared/app-components/charts/pie-chart/pie-chart.component.ts
Labels: enhancement

#149 Feature/jordan
  barista-web/src/app/app.module.ts
  barista-web/src/app/features/home/home.component.html
  barista-web/src/app/features/home/home.component.ts
  barista-web/src/app/features/home/temporary_display_data.ts
  barista-web/src/app/shared/app-components/charts/line-chart/line-chart.component.html
  barista-web/src/app/shared/app-components/charts/line-chart/line-chart.component.scss
  barista-web/src/app/shared/app-components/charts/line-chart/line-chart.component.spec.ts
  barista-web/src/app/shared/app-components/charts/line-chart/line-chart.component.ts
  barista-web/src/app/shared/layout/header/header.component.html
Labels: enhancement

#154 Merge front end design into dashboard
  barista-web/src/app/features/home/home.component.html
  barista-web/src/app/features/home/home.component.scss
  barista-web/src/app/features/home/home.component.ts
  barista-web/src/app/shared/layout/header/header.component.html
  barista-web/src/app/shared/layout/header/header.component.scss
  barista-web/src/assets/images/help-circle-outline.svg
Labels: enhancement

#160 Improve Dashboard UI and Display Correct Charts
  barista-api/src/controllers/stats/stats.controller.ts
  barista-web/src/app/features/home/home.component.html
  barista-web/src/app/features/home/home.component.scss
  barista-web/src/app/features/home/home.component.ts
  barista-web/src/app/features/projects/project-details/project-stats/project-stats.component.ts
  barista-web/src/app/shared/api/api/stats-api.service.ts
  barista-web/src/app/shared/app-components/charts/gauge-chart/gauge-chart.component.html
  barista-web/src/app/shared/app-components/charts/gauge-chart/gauge-chart.component.ts
  barista-web/src/app/shared/app-components/charts/horizontal-bar-chart/horizontal-bar-chart.component.html
  barista-web/src/app/shared/layout/header/header.component.html
  barista-web/src/app/shared/layout/header/header.component.scss
  barista-web/src/assets/images/barista_logo.png
  barista-web/src/assets/images/barista_logo_text_removed.png
Labels: enhancement

#165 disabled inputs based on information entered
  barista-web/src/app/features/projects/project-details/project-details.component.html
Labels: enhancement

#164 Feature/jorden/signin header
  barista-web/src/app/app-routing.module.ts
  barista-web/src/app/app.component.scss
  barista-web/src/app/features/signin/signin.component.html
  barista-web/src/app/features/signin/signin.component.scss
  barista-web/src/app/features/signin/signin.component.ts
  barista-web/src/app/shared/helpers/AuthInterceptor.ts
  barista-web/src/app/shared/layout/header/header.component.html
  barista-web/src/app/shared/layout/header/header.component.ts
Labels: bug, enhancement

#180 changes 'Dashboard' button to 'Home' button
  barista-web/src/app/shared/layout/header/header.component.html
Labels: enhancement

#182 Feature pkn4645 status badges
  README.md
  doc/barista-docs/docusaurus.config.js
  doc/local-dev-environment.md
Labels: documentation

#181 Feature/stat controller
  barista-api/src/controllers/stats/stats.controller.ts
  barista-web/src/app/features/home/home.component.ts
  barista-web/src/app/shared/api/api/stats-api.service.ts
Labels: enhancement

#179 Condense and clean front page UI
  barista-web/src/app/features/home/home.component.html
  barista-web/src/app/features/home/home.component.scss
  barista-web/src/app/features/home/home.component.ts
  barista-web/src/app/shared/app-components/charts/gauge-chart/gauge-chart.component.html
  barista-web/src/app/shared/app-components/charts/gauge-chart/gauge-chart.component.ts
Labels: enhancement

#183 put the username in a dropdown
  barista-web/src/app/shared/layout/header/header.component.html
  barista-web/src/app/shared/layout/header/header.component.scss
  barista-web/src/styles/_variables.scss
Labels: enhancement

#186 Added SQL parameter capabilities
  barista-api/src/controllers/stats/stats.controller.ts
  barista-web/src/app/features/home/home.component.ts
  barista-web/src/app/shared/api/api/stats-api.service.ts
Labels: enhancement

#185 Add Dataset Buttons to Home
  barista-web/src/app/features/home/home.component.html
  barista-web/src/app/features/home/home.component.scss
  barista-web/src/app/features/home/home.component.ts
Labels: enhancement

#187 Feature/text styling
  barista-web/src/app/app.component.scss
  barista-web/src/app/features/home/home.component.scss
  barista-web/src/app/shared/app-components/help-menu/help-menu.component.html
  barista-web/src/app/shared/app-components/help-menu/help-menu.component.scss
  barista-web/src/app/shared/layout/header/header.component.html
  barista-web/src/app/shared/layout/header/header.component.scss
  barista-web/src/app/shared/layout/header/header.component.ts
  barista-web/src/assets/images/information-circle-outline-click.svg
  barista-web/src/assets/images/person-circle-outline-click.svg
  barista-web/src/styles/_variables.scss
Labels: enhancement

#188 Api fix
  barista-api/src/controllers/stats/stats.controller.ts
  barista-web/src/app/features/home/home.component.html
  barista-web/src/app/features/home/home.component.ts
  barista-web/src/app/shared/api/api/stats-api.service.ts
Labels: enhancement

#190 Clean up dashboard with suggestions from Shark Tank
  barista-web/src/app/features/home/home.component.html
  barista-web/src/app/features/home/home.component.scss
  barista-web/src/app/shared/app-components/charts/chart-base/chart-base.component.ts
  barista-web/src/app/shared/app-components/charts/gauge-chart/gauge-chart.component.ts
Labels: enhancement

#197 Feature/loading icon
  barista-web/src/app/features/auth/auth.service.ts
  barista-web/src/app/features/home/home.component.html
  barista-web/src/app/features/home/home.component.ts
  barista-web/src/app/shared/helpers/AuthInterceptor.ts
Labels: enhancement

#196 Refactor Dashboard
  barista-web/src/app/app.module.ts
  barista-web/src/app/features/home/banner/banner.component.spec.ts
  barista-web/src/app/features/home/banner/banner.component.ts
  barista-web/src/app/features/home/chart-bar-horizontal/chart-bar-horizontal.component.spec.ts
  barista-web/src/app/features/home/chart-bar-horizontal/chart-bar-horizontal.component.ts
  barista-web/src/app/features/home/chart-bar-vertical/chart-bar-vertical.component.spec.ts
  barista-web/src/app/features/home/chart-bar-vertical/chart-bar-vertical.component.ts
  barista-web/src/app/features/home/chart-gauge/chart-gauge.component.spec.ts
  barista-web/src/app/features/home/chart-gauge/chart-gauge.component.ts
  barista-web/src/app/features/home/home.component.html
  barista-web/src/app/features/home/home.component.scss
  barista-web/src/app/features/home/home.component.ts
  barista-web/src/app/shared/app-components/help-menu/help-menu.component.html
  barista-web/src/app/shared/app-components/help-menu/help-menu.component.scss
  barista-web/src/app/shared/interfaces/Threshold.ts
  barista-web/src/app/shared/layout/header/header.component.html
  barista-web/src/app/shared/layout/header/header.component.scss
  barista-web/src/assets/images/help-circle-outline.svg
  barista-web/src/assets/images/information-circle-outline-click.svg
  barista-web/src/assets/images/information-circle-outline.svg
  barista-web/src/assets/images/person-circle-outline-click.svg
  barista-web/src/assets/images/person-circle-outline.svg
Labels: enhancement

#203 Feature/legends customization
  barista-web/src/app/features/projects/project-details/project-stats/project-stats.component.ts
Labels: enhancement

#204 Project stats page update
  barista-web/src/app/features/home/home.component.scss
  barista-web/src/app/features/projects/project-details/project-stats/project-stats.component.html
  barista-web/src/app/features/projects/project-details/project-stats/project-stats.component.scss
  barista-web/src/app/features/projects/project-details/project-stats/project-stats.component.ts
Labels: enhancement
